### ISSUE TITLE
Could not register katakana tokenizer!

### ISSUE THREAD

**Issue by slametapr** [Gnurou/tagainijisho#175]
I use fedora 24. I got "Could not register katakana tokenizer!" in terminal, and the kanji reading is not displayed.
![screenshot from 2016-07-21 09-53-35](https://cloud.githubusercontent.com/assets/11130882/17009890/65ca9a66-4f29-11e6-9767-6194483d8f31.png)

**Comment by Gnurou** [comment]
Are you using some package, or compiling it yourself?

If the latter, please add "-DEMBED_SQLITE=1" to your cmake command. This will compile and embed SQLite instead of using the version of your system. This will also be the default behavior on future releases.

**Comment by slametapr** [comment]
i installed it from official fedora repo. 
so the only way is compile it myself, right?

**Comment by Gnurou** [comment]
Packages provided by the Fedora repo should be working out-of-the-box. I suggest you report the issue there with the compilation hint I gave above. That way they will be able to issue a fixed package.

**Comment by slametapr** [comment]
ah, okay.. thanks for the response..

**Comment by gabriel-hackerdou** [comment]
I'm facing the same issue on Fedora 24 and 25.
It seems that the problem is the use of sqlite's two arg version of fts3_tokenizer(). Since 3.11 release this function was removed for security reasons: http://sqlite.org/releaselog/3_11_0.html, and this function can only be enabled at compiling time with SQLITE_ENABLE_FTS3_TOKENIZER flag.
Fedora packages aren't compiled with this flag, making Tagaini Jisho unable to register the katakana tokenizer.

**Comment by Gnurou** [comment]
That makes embedding SQLite a necessity then. Tagaini absolutely requires its custom tokenizer.

**Comment by gabriel-hackerdou** [comment]
The issue was reported to fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1395381

I added information about compiling with -DEMBED_SQLITE=1. I compiled with this flag and everything works good.

**Comment by Akeru** [comment]
@Gnurou Maybe not, quoting the SQLite release note :

Beginning with SQLite version 3.12.0, the second form of fts3_tokenizer() can also be activated at run-time by calling sqlite3_db_config(db,SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER,1,0).

This might be a good workaround since package maintainers often don't like to embed dependencies.

**Comment by gabriel-hackerdou** [comment]
@Akeru  I see this workaround was added in f248ff5cf018e6d978dfd3e4501839cf8a9c17ae:
src/sqlite/sqlite3ext.cc 

+#ifdef SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER
+	sqlite3_db_config(db, SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER, 1, NULL);
+#endif

though this code Is not yet in Tagaini 1.0.3 source,

**Comment by Akeru** [comment]
Indeed, this was fixed after the latest release it seems. Time for a new one I guess @Gnurou 😄

**Comment by Gnurou** [comment]
It has been time for quite some time actually! I just cannot find the time to fix the last bugs remaining... :'(
